#ifndef __BACKPORT_UAPI_LINUX_GENETLINK_H
#define __BACKPORT_UAPI_LINUX_GENETLINK_H
#include_next <uapi/linux/genetlink.h>

#if LINUX_VERSION_CODE < KERNEL_VERSION(4,6,0)
#define GENL_UNS_ADMIN_PERM     0x10
#endif /* LINUX_VERSION_CODE < KERNEL_VERSION(4,6,0) */
#endif /*__BACKPORT_UAPI_LINUX_GENETLINK_H */
